name: Deploy

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1182

      - name: Install node dependencies
        run: npm ci

      - name: Test
        run: npm run ci

      - name: Build
        run: |
          npm run release

      - uses: actions/upload-artifact@v3
        with:
          name: build-artefact
          path: ./resources/public/
          retention-days: 1

  DeployStaging:
    name: Deploy to Staging
    needs: [Build]
    runs-on: ubuntu-latest

    environment:
      name: Staging
      url: 'https://staging.deepumohan.com/games/2048'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artefact
          path: ~/artefact/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: publish-to-s3-action

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ~/artefact/ s3://staging.deepumohan.com/games/2048/

  DeployProd:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStaging]
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: 'https://deepumohan.com/games/2048'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artefact
          path: ~/artefact/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: publish-to-s3-action

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ~/artefact/ s3://deepumohan.com/games/2048/
